Repository codeit-sprint-fullstack/5-sprint-mission-be, pull requests merged in 2025-02, with the labels that each got.

#16 [김승우] Sprint6,7
  .gitignore
  README.md
  app.js
  package.json
  prisma/migrations/20250201043103_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  requests/article.http
Labels: 매운맛🔥, 최종 제출

#24 [최은비] sprint7
  .gitignore
  app.js
  http/users.http
  index.js
  package-lock.json
  package.json
  prisma/Articles/index.js
  prisma/Products/index.js
  prisma/migrations/20250122073606_init/migration.sql
  prisma/migrations/20250122153456_add_product_schema/migration.sql
  prisma/migrations/20250122153843_modify_for_migration/migration.sql
  prisma/migrations/20250122164250_product_id_cascade_ondelete/migration.sql
  prisma/migrations/20250122170224_seperate_comments/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/mock/mock_article.js
  prisma/mock/mock_article_comment.js
  prisma/mock/mock_product.js
  prisma/mock/mock_product_comment.js
  prisma/schema.prisma
  prisma/seed.js
  routes/article_router.js
  routes/product_router.js
Labels: 매운맛🔥, 최종 제출

#9 [이동혁] sprint7
  mission07/.gitignore
  mission07/app.js
  mission07/http/article.http
  mission07/http/comment.http
  mission07/http/products.http
  mission07/http/users.http
  mission07/mock/migrations/20250120080010_npm_init/migration.sql
  mission07/mock/migrations/20250120080539_init_new/migration.sql
  mission07/mock/migrations/migration_lock.toml
  mission07/mock/schema.prisma
  mission07/package-lock.json
  mission07/package.json
  mission07/prisma/migrations/20250122061530_panda_market/migration.sql
  mission07/prisma/migrations/20250122091343_date_add/migration.sql
  mission07/prisma/migrations/20250123012502_add_article/migration.sql
  mission07/prisma/migrations/20250123014026_author_id_not_required/migration.sql
  mission07/prisma/migrations/20250123024646_author_id_not_required_2/migration.sql
  mission07/prisma/migrations/20250123054456_add_page_in_comment/migration.sql
  mission07/prisma/migrations/20250123061430_comment_separation/migration.sql
  mission07/prisma/migrations/20250123063742_comment_integration/migration.sql
  mission07/prisma/migrations/migration_lock.toml
  mission07/prisma/mock.js
  mission07/prisma/schema/Article.prisma
  mission07/prisma/schema/Comment.prisma
  mission07/prisma/schema/Product.prisma
  mission07/prisma/schema/schema.prisma
  mission07/prisma/seed.js
  mission07/prismaClient.js
  mission07/routes/article/controller.js
  mission07/routes/article/service.js
  mission07/routes/comment/controller.js
  mission07/routes/comment/service.js
  mission07/routes/index.js
  mission07/routes/product/controller.js
  mission07/routes/product/service.js
  mission07/structs.js
Labels: 매운맛🔥, 최종 제출

#19 [김희성]sprint7
  .gitignore
  package-lock.json
  package.json
  prisma/migrations/20250126065721_test1/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema/Article.prisma
  prisma/schema/ArticleLike.prisma
  prisma/schema/Comment.prisma
  prisma/schema/Product.prisma
  prisma/schema/ProductLike.prisma
  prisma/schema/User.prisma
  prisma/schema/schema.prisma
  prisma/seed.js
  product.http
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  request.http
  server.js
  server/config/mongoDB.js
  server/config/prismaClient.js
  server/models/product.js
  server/routes/articles.js
  server/routes/comments.js
  server/routes/index.js
  server/routes/products.js
  structs.js
Labels: 매운맛🔥, 최종 제출

#26 [박세정] sprint7
  .gitignore
  app.js
  http/article.http
  http/comment.http
  mock/mock.js
  mock/schema.prisma
  mock/seed.js
  package-lock.json
  package.json
  prisma/migrations/20250131005304_modelling_of_article_comment/migration.sql
  prisma/migrations/20250131163138_patch_prisma_model/migration.sql
  prisma/migrations/20250131165507_add_fk/migration.sql
  prisma/migrations/20250131165919_patch_fk/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  routes/article/controller.js
  routes/article/service.js
  routes/comment/controller.js
  routes/comment/service.js
  structs.js
Labels: 미완성🫠, 순한맛🐑

#25 [봉재완] sprint7
  mission7/.gitignore
  mission7/README.md
  mission7/config/db.js
  mission7/config/seed.js
  mission7/controllers/articleController.js
  mission7/controllers/commentController.js
  mission7/controllers/productController.js
  mission7/models/article.js
  mission7/models/comment.js
  mission7/models/product.js
  mission7/package-lock.json
  mission7/package.json
  mission7/routes/articleRoutes.js
  mission7/routes/commentRoutes.js
  mission7/routes/productRoutes.js
  mission7/server.js
Labels: 순한맛🐑, 최종 제출

#5 [정하윤] sprint6
  .github/pull-request-template.md
  .github/workflows/auto-label-assign.yml
  .gitignore
  README.md
  app.js
  models/Product.js
  package-lock.json
  package.json
  requests.http
  routes/index.js
  routes/products/productController.js
  routes/products/productRoutes.js
Labels: 매운맛🔥, 최종 제출

#12 [정한샘] sprint6
  .gitignore
  app.js
  package-lock.json
  package.json
  prisma/migrations/20250122063728_sprint7/migration.sql
  prisma/migrations/20250122081756_sprint7/migration.sql
  prisma/migrations/20250123014310_sprint7/migration.sql
  prisma/migrations/migration_lock.toml
  routes/index.js
  routes/product/controller/product.controller.js
  routes/product/index.js
  routes/product/model/Product.js
  routes/product/service/product.service.js
Labels: 매운맛🔥, 최종 제출
